// <auto-generated />
using System;
using Cleanifico.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cleanifico.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CleanificoDbContext))]
    [Migration("20260825130433_InitialCleanificoPersistence")]
    partial class InitialCleanificoPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Cleanifico.Domain.CleaningTypes.CleaningType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .IsFixedLength()
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .UseCollation("utf8mb4_0900_ai_ci");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CleaningTypes_Code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_CleaningTypes_Name");

                    b.HasIndex("IsActive", "SortOrder", "Name")
                        .HasDatabaseName("IX_CleaningTypes_Status_SortOrder_Name");

                    b.ToTable("CleaningTypes", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                });
#pragma warning restore 612, 618
        }
    }
}
